services:
  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: vikasbagri
      POSTGRES_PASSWORD: vikasbagri
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5431:5432"
    networks:
      - db
    restart: unless-stopped

  vikas-demo-api:
    container_name: vikas-demo-api-container
    image: bagrivikas/vikas-demo-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/database1
    ports:
      - "8082:8081"
    networks:
      - db
    depends_on:
      - postgres
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: